window.EASY_ACCOUNT_SHELL_CONFIG = {
  brand: {
    name: "Yee账通",
    logo: "./assets/logo-txt@3x.png",
    icon: "./assets/logo.png",
  },
  user: { name: "运营账号", initials: "OU" },
  activeTabId: "role-management",
  tabs: [
    { id: "brand-management", label: "品牌管理", pinned: true, closable: false },
    { id: "account-management", label: "账号管理" },
    { id: "account-query", label: "账户查询" },
    { id: "role-management", label: "角色管理" },
    { id: "platform-account", label: "平台账号管理" },
    { id: "store-management", label: "门店管理" },
    { id: "enterprise-unit", label: "企业单位管理" },
    { id: "supplier-management", label: "供应商管理" },
    { id: "organization-management", label: "组织机构管理" },
    { id: "fee-allocation", label: "费用分账" },
  ],
  menu: [
    {
      id: "enterprise-management",
      label: "企业管理",
      icon: "ApartmentOutlined",
      open: true,
      children: [
        { id: "brand-management", label: "品牌管理" },
        { id: "store-management", label: "门店管理" },
        { id: "enterprise-unit", label: "企业单位管理" },
        { id: "supplier-management", label: "供应商管理" },
        { id: "organization-management", label: "组织机构管理" },
        { id: "role-management", label: "角色管理", active: true },
        { id: "account-management", label: "账号管理" },
        { id: "platform-account", label: "平台账号管理" },
      ],
    },
    {
      id: "finance-management",
      label: "财务管理",
      icon: "AccountBookOutlined",
      open: true,
      children: [
        { id: "account-management-finance", label: "账户管理" },
        { id: "fee-allocation", label: "费用分账" },
        { id: "lock-allocation", label: "统收分账" },
        { id: "manual-allocation", label: "手动分账" },
        { id: "transaction-query", label: "交易记录查询" },
        { id: "account-flow-query", label: "账户流水查询" },
      ],
    },
  ],
  footer: "",
};
